### ISSUE TITLE
CC2017好像不能用

### ISSUE THREAD

**Issue by ayumitsuty** [Smallpath/Memory#24]

**Comment by Smallpath** [comment]
？ 你找找脚本文件夹Sp_memory/tempFile里有没有error.txt，没有的话说明你用的脚本不是最新版的，最新的在[这里](http://pan.baidu.com/s/1nuHU3Ex)下

**Comment by ayumitsuty** [comment]
卧槽,可以用,为什么那个MG包这么强,比微博上那个多多了

**Comment by Smallpath** [comment]
某位用户发给我的，微博上没找到他叫啥，所以没发微博，直接传网盘去了

没其他问题的话，我先把这个issue关了
