### ISSUE TITLE
not run correctly on win 10 ae 14.0.1.5

### ISSUE THREAD

**Issue by msongz** [Smallpath/Memory#25]
---------------------------
Script Alert
---------------------------
1319Error: After Effects error: Unable to set “file”. Path is not valid. Path: “D:\AE17\Adobe After Effects CC 2017\Support Files\Scripts\ScriptUI Panels\Sp_memory\image\33\NULL_.png”
---------------------------
确定   
---------------------------

**Comment by Smallpath** [comment]
是用的以前的版本么？  新版已经加上[CC2017的支持](https://github.com/Smallpath/Memory/blob/master/memory.jsx#L1004)了, 最新的在[这里](http://pan.baidu.com/s/1nuHU3Ex)下
