### ISSUE TITLE
CC 2017 mac版下表达式翻译无法编辑

### ISSUE THREAD

**Issue by unsad** [Smallpath/Memory#26]
错误文件是这样：
Catched-Line# 1580	Happened-Line# 1579	Error: After Effects错误: 由于参数 2，无法调用“setInterpolationTypeAtKey”。NaN 不是无符号整数。
Catched-Line# 1132	Happened-Line# 1093	ReferenceError: 函数 layers.canAddProperty 未定义

另外有个小问题，右键展开菜单点开表达式后菜单无法关闭，需要再次右键新展开菜单才能关闭。

**Comment by Smallpath** [comment]
表达式翻译的白名单是放在`~/Library/Application Support/`中的，查了一下发现是Mac上写文件失败，感觉是AE没拿到这个目录的权限。我先做下权限方面的尝试。

**Comment by unsad** [comment]
好的，辛苦秋风大大
在 2017年2月13日，上午12:47，Smallpath <notifications@github.com<mailto:notifications@github.com>> 写道：


表达式翻译的白名单是放在~/Library/Application Support/中的，查了一下发现是Mac上写文件失败，感觉是AE没拿到这个目录的权限。我先做下权限方面的尝试。

**Comment by Smallpath** [comment]
囧，找到解决办法了才记起来adobe砍了脚本权限，现在2015及以上本来就用不了表达式翻译，不好意思

**Comment by Smallpath** [comment]
AE 13.6 changes:
> The valueAtTime() scripting method now waits for time-intensive expressions, like sampleImage, to finish evaluating before it returns the result.

发现13.6及以后表达式翻译可以用了

**Comment by Smallpath** [comment]
已解决, 不过目前得在sp_memory中右键唤出使用, 单独版暂时不能在mac上用
