### ISSUE TITLE
无法存储包含空预合成的元素

### ISSUE THREAD

**Issue by BrownBichon** [smallpath/memory#30]
如果要存储的元素中包含空的预合成就会报错

> Line #1409 Error: After Effects error: Value 1 out of range 1 to 0.

感觉空的预合成在做替换图片类的预设或者模板的时候还是挺实用的。

**Comment by smallpath** [comment]
收到

**Comment by smallpath** [comment]
已修, 现在的报错中的行号就是脚本文件里的代码行号, 定位起来比以前方便多了, v3.0的tag还没打, 欢迎提BUG

**Comment by smallpath** [comment]
另外我列了一下v3.1的详细更新历史, 欢迎尝试和测试  https://smallpath.me/ae-scripting-memory-v3.1

**Comment by BrownBichon** [comment]
Get，定位错误确实很方便，我还看了一下源码，可惜不会改。。
因为这个bug，我还注意到一点，在元素没有正确生成，脚本报错的情况下，默认还是会生成预览图像序列，多出错几次之后就有许多无用的预览序列存在本地。不知道可不可以调整一下执行顺序，先写入xml，再生成预览。

**Comment by smallpath** [comment]
这是因为存xml时需要提前得知预览目标文件是否存在, 否则会覆盖已有元素的预览图片, 另外v3.1的进度条和这个存储的顺序耦合度比较高, 我看看怎么改.  不过预览序列都是100*60的图片,  每个在10KB以内, 不会占用太多地方

**Comment by BrownBichon** [comment]
嗯，也不是什么大问题，只是那天测试这个bug原因的时候生成了一堆，所以想到可不可以直接改变执行顺序。如果bug修好也就没这个问题啦😂
